
Initialization Phase
================================================================
error: communication error with bot: read failed, errno was: 0 (Success)
Bot error output was:
Traceback (most recent call last):
  File "MyBot.py", line 54, in <module>
    hlt_map = scoreMap(game,game.me.shipyard.position,game.me.shipyard.position,r)
  File "MyBot.py", line 44, in scoreMap
    htl_map = scoreMap(game,game.me.shipyard.position,d,radius,hlt_map)
  File "MyBot.py", line 44, in scoreMap
    htl_map = scoreMap(game,game.me.shipyard.position,d,radius,hlt_map)
  File "MyBot.py", line 44, in scoreMap
    htl_map = scoreMap(game,game.me.shipyard.position,d,radius,hlt_map)
  [Previous line repeated 985 more times]
  File "MyBot.py", line 32, in scoreMap
    directions = curPoint.get_surrounding_cardinals()
  File "/home/worker/Halite/apiserver/worker/tmptatvrx3w/720_0_klaywittler/hlt/positionals.py", line 81, in get_surrounding_cardinals
    return [self.directional_offset(current_direction) for current_direction in Direction.get_all_cardinals()]
  File "/home/worker/Halite/apiserver/worker/tmptatvrx3w/720_0_klaywittler/hlt/positionals.py", line 81, in <listcomp>
    return [self.directional_offset(current_direction) for current_direction in Direction.get_all_cardinals()]
  File "/home/worker/Halite/apiserver/worker/tmptatvrx3w/720_0_klaywittler/hlt/positionals.py", line 75, in directional_offset
    return self + Position(*direction)
  File "/home/worker/Halite/apiserver/worker/tmptatvrx3w/720_0_klaywittler/hlt/positionals.py", line 84, in __add__
    return Position(self.x + other.x, self.y + other.y)
RecursionError: maximum recursion depth exceeded

